name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Use a stable runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear Runner Cache
        run: |
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /opt/actions-runner

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
